version: 0.10.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: source\Inspector.sln

test: off

artifacts:
  - path: source\bin
    type: zip
    name: inspector 